### ISSUE TITLE
Can't group contacts without 'names' attribute

### ISSUE THREAD

**Issue by analoginterface0** [mbideau/vcardtools#11]
Greetings,

I want to deduplicate contacts based only on number or email match. I've tried 
`python vcardtools.py -m -t 80 -i 11 -a 'mobile' -a 'email' DIR *.vcf`
but it throws this error:
```
Traceback (most recent call last):
  File "GITDIR/vcardtools_mbideau/vcardtools.py", line 281, in <module>
    main()
  File "GITDIR/vcardtools_mbideau/vcardtools.py", line 219, in main
    vcards_grouped, vcards_not_grouped = get_vcards_groups(vcards)
  File "GITDIR/vcardtools_mbideau/vcardlib.py", line 1476, in get_vcards_groups
    number_of_names = len(mappings['attributes']['names'])
KeyError: 'names'
```

unfortunately, using `-x` flag doesn't do what I it want to do (i.e. group contacts with numbers like +0601234-56789 and 0123456789)
Please help!
N.B. replaced actual parent directory with GITDIR

**Comment by mbideau** [comment]
Hi @analoginterface0 and thank you for your feedback again.
Glad that you appreciate the results/tool.

Sorry that I took my ages to reply...

I send you an email from my personal address, check your spam folders (big corps don't like my tiny mail hosting) :sweat_smile: 

About the bug `KeyError: 'tel'` could you please send me an email with the input files, the output files, and the log in debug mode (`-l DEBUG`), like you have done before ? It would help me reproduce the bug/exception. Thank you in advance.

**Comment by analoginterface0** [comment]
> About the bug `KeyError: 'tel'` could you please send me an email with the input files, the output files, and the log in debug mode (`-l DEBUG`), like you have done before ? It would help me reproduce the bug/exception. Thank you in advance.

okay, I'm on it
