### ISSUE TITLE
Failure with empty vCard entry in file

### ISSUE THREAD

**Issue by kkrugler** [mbideau/vcardtools#9]
When processing a large file (> 2000 entries), I got this error:
```
Traceback (most recent call last):
  File "vcardtools.py", line 281, in <module>
    main()
  File "vcardtools.py", line 214, in main
    args.no_remove_name_in_email \
  File "/Users/kenkrugler/git/vcardtools/vcardlib.py", line 810, in get_vcards_from_files
    selected_name = select_most_relevant_name(available_names)
  File "/Users/kenkrugler/git/vcardtools/vcardlib.py", line 374, in select_most_relevant_name
    raise ValueError("Trying to select a name from an empty list of names")
ValueError: Trying to select a name from an empty list of names
```

I added some debugging logging (would be useful to dump out card and count when an exception happens), and the vCard entry was `<VCARD| [<VERSION{}3.0>, <PRODID{}-//Apple Inc.//macOS 11.2.3//EN>, <N{}    >]>`

I grepped the input file, and found it was this entry:

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//macOS 11.2.3//EN
N:;;;;
END:VCARD
```

After removing it from the file, the code ran to completion.

**Comment by axelsimon** [comment]
Same here, i got `Trying to select a name from an empty list of names` because of an entry that was just
```
BEGIN:VCARD
VERSION:2.1
END:VCARD
```

After removing it (thank you DEBUG log level!) my big vcf file was parsed fine.

These seem to be spat out by contacts exports every now and then, it would probably be worth accounting for them if you can be bothered @mbideau :)

**Comment by mbideau** [comment]
Hi @kkrugler and @axelsimon 

First my apologies for my super late reply.
Thanks a lot for your feedback, it is really appreciated 🙏 
I'll look into it as soon as I have some free time to do it.

I really want this program to help users, so I want to handle those cases in a user friendly maner.

I'll keep you posted when I will have a bug fix.
